spring:
  application:
    name: mcp-config-example
# TODO: MCP server 启用后报错，本示例暂不启用
  ai:
    mcp:
      server:
        enabled: false

spring.ai.alibaba.mcp.router:
  enabled: true
  discovery-type: database  # file, database, nacos
  services:
    - name: weather-service
      description: "天气查询服务"
      protocol: "http"
      version: "1.0.0"
      endpoint: "http://localhost:8080/weather"
      enabled: true
      tags:
        - "weather"
        - "api"
    - name: translation-service
      description: "翻译服务"
      protocol: "http"
      version: "2.0.0"
      endpoint: "http://localhost:8081/translate"
      enabled: true
      tags:
        - "translation"
        - "nlp"
    - name: disabled-service
      description: "已禁用的服务"
      protocol: "http"
      version: "1.0.0"
      endpoint: "http://localhost:8082/disabled"
      enabled: false
      tags:
        - "test"
  database:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    tableName: mcp_server_info
